# Generated by Django 4.1.1 on 2022-12-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='businessTask',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_basicdetails',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personalTask',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personal_basicdetails',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_owner',
        ),
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
