# Generated by Django 4.1.1 on 2022-11-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0002_rename_user_profile_personal_businessprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='business_name',
            new_name='business_basicdetails',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='personal',
            new_name='personal_basicdetails',
        ),
    ]
