# Generated by Django 4.1.1 on 2022-12-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='businessTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.task'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personalTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.task'),
        ),
    ]
