# Generated by Django 4.1.1 on 2022-12-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0004_alter_businessprofile_businesstask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.subtask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='task_file_folder'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='task_image_folder'),
        ),
    ]
