# Generated by Django 4.1.1 on 2022-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0006_alter_task_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_owner',
            field=models.CharField(max_length=150),
        ),
    ]
