# Generated by Django 4.1.1 on 2022-12-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0008_remove_businessprofile_businesstask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.task'),
        ),
    ]
