# Generated by Django 4.1.1 on 2022-12-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0009_remove_task_subtask_subtask_task_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
