# Generated by Django 4.1.1 on 2022-12-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0010_task_task_dateupdated_alter_task_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_progress',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
