# Generated by Django 4.1.1 on 2022-12-08 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0011_task_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='businessProjectowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.businessprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='personalProjectowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.CharField(default=1970, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='businessTaskowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.businessprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='personalTaskowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.profile'),
        ),
    ]
