# Generated by Django 4.1.1 on 2022-12-21 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0012_remove_project_id_project_businessprojectowner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_owner', models.CharField(max_length=150)),
                ('board_name', models.CharField(max_length=150)),
                ('board_description', models.TextField(blank=True, default=None, null=True)),
                ('board_file', models.FileField(blank=True, default=None, null=True, upload_to='task_file_folder')),
                ('board_image', models.ImageField(blank=True, default=None, null=True, upload_to='task_image_folder')),
                ('board_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('board_inprogress', models.BooleanField(blank=True, default=False, null=True)),
                ('board_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('board_date', models.DateTimeField(auto_now_add=True)),
                ('board_dateUpdated', models.DateTimeField(auto_now=True)),
                ('board_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.project')),
                ('businessBoardowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.businessprofile')),
                ('personalBoardowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='businessTaskowner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='task',
            name='personalTaskowner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_dateUpdated',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_project',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
        migrations.AddField(
            model_name='task',
            name='task_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytodoapp.board'),
        ),
    ]
