# Generated by Django 4.1.1 on 2023-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0014_project_project_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
