# Generated by Django 4.1.1 on 2023-01-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0016_remove_task_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
